window.KIKZ_DAYS = [
  {
    "id":1,"name":"UPPER STRENGTH","color":"#C92A2A","image":"assets/day1.png","focus":"Chest • Back • Shoulders • Core",
    "warmup":[["Bike / Incline Walk","4 min moderate",""],["Band Pull-Apart","2 × 15",""],["Scapular Push-up","2 × 10",""],["T-Spine Rotation","2 × 8 / side",""]],
    "workout":[["Incline Dumbbell Press","3 × 6–8","RIR 1–2","2–3 min","https://www.youtube.com/watch?v=8iPEnn-ltC8"],["Chest-Supported Row","3 × 6–8","RIR 1–2","2–3 min","https://www.youtube.com/watch?v=bsx8PIGIuaI"],["Overhead Press","3 × 6–8","RIR 1–2","2–3 min","https://www.youtube.com/watch?v=_RlRDWO2jfg"],["Neutral-Grip Lat Pulldown","3 × 8–10","RIR 1–2","90 sec","https://www.youtube.com/watch?v=aoHXhJ2x2BQ"],["Cable Lateral Raise","3 × 12–15","RIR 1–2","60 sec","https://www.youtube.com/watch?v=SgyUoY0IZ7A&t=477s"],["Cable Face Pull","3 × 12–15","RIR 1–2","60 sec","https://www.youtube.com/watch?v=qfc70k40318"],["Zone 2 Cardio","10–15 min","RPE 5–6","Optional","https://www.youtube.com/results?search_query=zone+2+cycling+beginner+technique"]],
    "mobility":[["Chest Stretch","30 sec / side","https://www.youtube.com/results?search_query=doorway+chest+stretch+technique"],["Lat Stretch","30 sec / side","https://www.youtube.com/results?search_query=kneeling+lat+stretch+technique"],["T-Spine Rotation","30 sec / side","https://www.youtube.com/results?search_query=open+book+thoracic+rotation+mobility"]]
  },
  {
    "id":2,"name":"LOWER STRENGTH","color":"#2864C7","image":"assets/day2.png","focus":"Quads • Hamstrings • Single-Leg • Stability",
    "warmup":[["Bike","5 min",""],["Ankle Rocks","2 × 10 / side",""],["90/90 Hip Rotation","2 × 8 / side",""],["World’s Greatest Stretch","1 × 4 / side",""]],
    "workout":[["Hack Squat","3 × 6–8","RIR 1–2","2–3 min","https://www.youtube.com/watch?v=4cxt_Tldugw"],["Romanian Deadlift","3 × 6–8","RIR 1–2","2–3 min","https://www.youtube.com/watch?v=SE-2Y-3a1pY"],["Bulgarian Split Squat","3 × 8 / leg","RIR 1–2","2 min","https://www.youtube.com/watch?v=bwhl_9jN_3o"],["Seated Leg Curl","3 × 10–12","RIR 1","90 sec","https://www.youtube.com/watch?v=ELOCsoDSmrg&t=1s"],["Leg Extension","2 × 12–15","RIR 1","60 sec","https://www.youtube.com/watch?v=YyvSfVjQeL0"],["Standing Calf Raise","3 × 10–15","RIR 1","60–90 sec","https://www.youtube.com/watch?v=-qsRtp_PbVM"],["Lateral Shuffle","3 × 20 sec","","","https://www.youtube.com/results?search_query=lateral+shuffle+change+of+direction+technique"],["Lateral Bound to Stick","3 × 4 / side","","","https://www.youtube.com/results?search_query=lateral+bound+stick+landing+technique"],["Crossover Step","3 × 20 sec","","","https://www.youtube.com/results?search_query=crossover+step+agility+technique"]],
    "mobility":[["Hip Flexor Stretch","40 sec / side","https://www.youtube.com/watch?v=vIDzsqJiAIo"],["Adductor Stretch","40 sec / side","https://www.youtube.com/results?search_query=adductor+stretch+technique"],["Calf Stretch","40 sec / side","https://www.youtube.com/watch?v=yZCfQ6YbAvA"]]
  },
  {
    "id":3,"name":"UPPER ATHLETIC","color":"#2F8F57","image":"assets/day3.png","focus":"Back • Chest • Arms • Rotation",
    "warmup":[["Bike","4–5 min",""],["Band External Rotation","2 × 12",""],["Scapular Pull-up","2 × 8",""],["T-Spine Rotation","2 × 6 / side",""]],
    "workout":[["Flat Dumbbell Press","3 × 8–10","RIR 1–2","2 min","https://www.youtube.com/watch?v=fGm-ef-4PVk&t=215s"],["One-Arm Cable Row","3 × 8–12","RIR 1–2","90 sec","https://www.youtube.com/watch?v=oSEYo6f3eWU"],["Pull-up / Assisted Pull-up","3 × 6–10","RIR 1","2 min","https://www.youtube.com/watch?v=Hdc7Mw6BIEE"],["Cable Fly","2 × 12–15","RIR 1","60 sec","https://www.youtube.com/watch?v=KJwiu8ttuZ0"],["Rear Delt Cable Fly","3 × 15–20","RIR 1","60 sec","https://www.youtube.com/watch?v=SL-2xNfEBog"],["Incline Dumbbell Curl","3 × 10–12","RIR 1","60–90 sec","https://www.youtube.com/watch?v=3FAvFJ0Vtag"],["Overhead Cable Triceps Extension","3 × 10–15","RIR 1","60–90 sec","https://www.youtube.com/watch?v=OpRMRhr0Ycc&t=193s"],["Bike Intervals","6 rounds • 20s hard + 70s easy","RPE 8 hard","8–12 min","https://www.youtube.com/results?search_query=bike+intervals+20+seconds+hard+70+seconds+easy"]],
    "mobility":[["Shoulder Stretch","30–40 sec / side","https://www.youtube.com/results?search_query=shoulder+stretch+technique"],["T-Spine Rotation","30–40 sec / side","https://www.youtube.com/results?search_query=open+book+thoracic+rotation+mobility"],["Lat Stretch","30–40 sec / side","https://www.youtube.com/results?search_query=kneeling+lat+stretch+technique"]]
  },
  {
    "id":4,"name":"ATHLETIC LOWER","color":"#C99A18","image":"assets/day4.png","focus":"Glutes • Power • Single-Leg Strength • Stability",
    "warmup":[["Bike","4 min",""],["Ankle Rock","2 × 10",""],["90/90 Hip Rotation","2 × 8",""],["Hip Opener","2 × 6 / side",""],["Lateral Shuffle","2 × 15 sec",""],["Pogo Hop","2 × 10",""]],
    "workout":[["Box Jump","3 × 3","","Full recovery","https://www.youtube.com/results?search_query=box+jump+technique"],["Lateral Bound to Stick","3 × 4 / side","","Full recovery","https://www.youtube.com/results?search_query=lateral+bound+stick+landing+technique"],["Front Squat","3 × 5–8","RIR 1–2","2–3 min","https://www.youtube.com/watch?v=v-mQm_droHg"],["Hip Thrust","3 × 8–10","RIR 1","2 min","https://www.youtube.com/watch?v=xDmFkJxPzeM"],["Reverse Lunge","3 × 8 / leg","RIR 1–2","90 sec","https://www.youtube.com/watch?v=9RNKFnd8Hbk"],["Single-Leg Romanian Deadlift","2 × 8 / leg","RIR 1–2","90 sec","https://www.youtube.com/watch?v=UFI-CG4NMU8"],["Lying Leg Curl","3 × 10–12","RIR 1","90 sec","https://www.youtube.com/watch?v=1Tq3QdYUuHs&t=2s"],["Seated Calf Raise","3 × 12–15","RIR 1","60 sec","https://www.youtube.com/watch?v=FEewFamWj4E"],["Sled Push","6 × 20 m","","60–90 sec","https://www.youtube.com/watch?v=PK3Xz3VemYw"]],
    "mobility":[["Hip Flexor Stretch","40 sec / side","https://www.youtube.com/watch?v=vIDzsqJiAIo"],["Adductor Stretch","40 sec / side","https://www.youtube.com/results?search_query=adductor+stretch+technique"],["Calf Stretch","40 sec / side","https://www.youtube.com/watch?v=yZCfQ6YbAvA"]]
  }
];